Cleanup
rhythmictech/terraform-aws-ecs-cluster pull request #6
Opened 2020-06-09 21:18 UTC by sblack4

I'm changing the names of outputs - this will be a major version bump!

- Changed `-` in names to `_`
- Added descriptions or comments to ignore tfsec
- Changed the example path to `examples/basic`
- Added new pre-commit stuff and GH action
- Added versioning

2020-06-10 13:26 UTC, cdaniluk requested changes
minor stuff. the bones are good.

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +# ecs_cluster module
```suggestion
# terraform-aws-ecs-cluster
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id = "${module.ecs_cluster.alb-sg-id}"
```suggestion
    security_group_id = module.ecs_cluster.alb-sg-id
```
surprised this got past the deprecation linter

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id = "${module.ecs_cluster.alb-sg-id}"
```suggestion
    security_group_id = module.ecs_cluster.alb-sg-id
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id = "${module.ecs_cluster.alb-sg-id}"
```suggestion
    security_group_id = module.ecs_cluster.alb-sg-id
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id        = "${module.ecs_cluster.ec2-sg-id}"
```suggestion
    security_group_id        = module.ecs_cluster.ec2-sg-id
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    source_security_group_id = "${module.ecs_cluster.alb-sg-id}"
```suggestion
    source_security_group_id = module.ecs_cluster.alb-sg-id
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id = "${module.ecs_cluster.ec2-sg-id}"
```suggestion
    security_group_id = module.ecs_cluster.ec2-sg-id
```

2020-06-10 13:26 UTC, cdaniluk commented on README.md
> +    security_group_id = "${module.ecs_cluster.alb-sg-id}"
answered my own question, this is the readme 🤦

2020-06-10 13:26 UTC, cdaniluk commented on ecs_instance_role.tf
> +  name_prefix        = "${substr(var.name, 0, 20)}-ec2-role-"
👍

2020-06-10 13:26 UTC, cdaniluk commented on ecs_instance_role.tf
> +  assume_role_policy = data.aws_iam_policy_document.ecs_instance_policy_document.json
sort

2020-06-10 13:26 UTC, cdaniluk commented on ecs_instance_role.tf
> +    local.base_tags,
why is `base_tags` still a thing in this refactor?

2020-06-10 13:26 UTC, cdaniluk commented on ecs_instance_role.tf
> +  policy      = var.instance_policy_document
the sort police are here.

2020-06-10 13:26 UTC, cdaniluk commented on ecs_instance_role.tf
> +  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
the sort police are here.

2020-06-10 13:26 UTC, cdaniluk commented on alb.tf
>    tags = merge(
not showing in the diff but we should phase our `base_tags` in the line below this

2020-06-10 13:26 UTC, cdaniluk commented on cluster.tf
>    tags = merge(
`base_tags` go away

2020-06-10 13:26 UTC, cdaniluk commented on cluster.tf
> +resource "aws_ecs_cluster" "ecs_cluster" {
this should probably be `this` but don't think it's worth it at this stage to fix.

2020-06-10 13:26 UTC, cdaniluk commented on examples/basic/main.tf
> +  region            = var.region
is region still actually needed?

2020-06-10 13:26 UTC, cdaniluk commented on launch_config.tf
> +    local.base_tags,
🚒

2020-06-10 13:26 UTC, cdaniluk commented on launch_config.tf
> +  service_name       = "com.amazonaws.${var.region}.cloudformation"
this can be computed from the provider rather than specified as a var

2020-06-10 13:26 UTC, cdaniluk commented on launch_config.tf
>    --region "${var.region}" || true
```suggestion
  --region "${local.region}" || true
```

2020-06-10 13:26 UTC, cdaniluk commented on launch_config.tf
>    --region "${var.region}" || true
(after you set a local per other feedback)

2020-06-10 13:26 UTC, cdaniluk commented on outputs.tf
> +output "alb_sg_id" {
```suggestion
output "security_group_alb" {
```

2020-06-10 13:26 UTC, cdaniluk commented on outputs.tf
> +output "ec2_sg_id" {
```suggestion
output "security_group_ec2" {
```

2020-06-10 13:26 UTC, cdaniluk commented on outputs.tf
> +output "cluster_id" {
```suggestion
output "ecs_cluster_id" {
```

2020-06-10 13:26 UTC, cdaniluk commented on outputs.tf
> +output "cluster_name" {
```suggestion
output "ecs_cluster_name" {
```

also some mad sorting issues in here

2020-06-10 13:26 UTC, cdaniluk commented on outputs.tf
>  output "cloudformation_asg_template" {
neat

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +variable "ec2_public_ip" {
```suggestion
variable "assign_ec2_public_ip" {
```
bools should have a verb

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  type        = string
```suggestion
  type        = bool
```
bools should be bools

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  type        = string
```suggestion
  type        = number
```

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  default     = 1
should we have a default for this or force a choice?

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +variable "instance_policy_document" {
no time for this now but I prefer to pass policies rather than policy docs

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  type        = string
```suggestion
  type        = number
```

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  type        = string
```suggestion
  type        = number
```

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +variable "region" {
x-nay on the region-ay

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +variable "ssh_pubkey" {
another thing we don't have time for but not sure why we aren't passing a proper keypair rather than the string..

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +  type        = string
```suggestion
  type        = number
```

2020-06-10 13:26 UTC, cdaniluk commented on variables.tf
> +locals {
crush this

2020-06-10 14:40 UTC, sblack4 commented on variables.tf
> +variable "region" {
gonezo

2020-06-10 14:51 UTC, smiller171 commented on variables.tf
> +variable "ssh_pubkey" {
passing in a file in terraform sounds messy as hell.

2020-06-10 18:51 UTC, sblack4 commented on variables.tf
> +variable "ssh_pubkey" {
🍨 https://github.com/rhythmictech/terraform-aws-ecs-cluster/blame/01eb465789420739c489417711dcc257c7d99e58/variables.tf#L46

2020-07-05 15:58 UTC, cdaniluk requested changes
I don't feel strongly on any of my suggested changes (minus the ever necessary sorting of things), so feel free to punt any with TODOs. I know this has turned into an unexpected beast.

One point worth considering.. since we are totally redoing this module, it won't be a straightforward upgrade process anyway. It might be a good opportunity to switch resources to `this` wherever possible. But, I also don't feel strongly about that.

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +  name_regex  = "^amzn2-ami-ecs-hvm-.*-x86_64-ebs"
This should probably be a var. There are other ECS AMIs one could use if one was into such things.

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +  name_regex  = "^amzn2-ami-ecs-hvm-.*-x86_64-ebs"
Come to think about it, I think you should leave this as is but then let the user specify an AMI ID and ignore this.

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +resource "aws_key_pair" "default" {
same as above, let the user specify a key name to use.

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +yum install -y aws-cfn-bootstrap
isn't this always present on amzn linux?

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +  name_prefix = "${var.name}-ec2-sg-"
```suggestion
  name_prefix = "${var.name}-ec2-sg"
```

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +resource "aws_security_group_rule" "ecs_ec2_ingress_from_alb" {
the sort police are here for you

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +resource "aws_security_group_rule" "ecs_ec2_egress_to_alb" {
and then there were sorted vars and the lord smiled.

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +resource "aws_security_group_rule" "self_to_ecs_ec2" {
sort

2020-07-05 15:58 UTC, cdaniluk commented on launch_config.tf
> +resource "aws_security_group_rule" "ecs_ec2_to_self" {
🗄️ another place where things are sorted

2020-07-05 17:47 UTC, sblack4 commented
I haven't fully vetted this but I'm about to use it and don't want to update everything from the `-` syntax to `_`

2020-07-05 18:01 UTC, merged